defaults:
  - model: small
  - data: sg2-ffhq
  - val: sg2-ffhq

device: "cuda:0"
train:
  loop:
    print_it: 100
    max_it: 1000000
    val_it: 5000
  opt:
    lr: 3.0e-4
    weight_decay: 1.0e-2
    betas: [0.9, 0.999]
