defaults:
  - model: small

device: "cuda:0"
data:
  bs: 32
  format: webdataset
  path: test_data/webdataset/{00000..1}.tar
  noise_scale: 0.75
  sg_pkl: 'https://api.ngc.nvidia.com/v2/models/nvidia/research/stylegan2/versions/1/files/stylegan2-ffhq-1024x1024.pkl'
  clip_variant: "ViT-B/32"
val:
  n_im_val_samples: 16
  text_val_samples: [
      "A photograph of a young man's with a beard",
      "A photograph of a old woman's face with grey hair",
      "A photograph of a child at a birthday party",
      "A picture of a face outside in bright sun in front of green grass",
      "This man has bangs arched eyebrows curly hair and a small nose",
      "A photo of Barack Obama",
      "An arctic explorer",
      "A clown's face covered in make up",
  ]
train:
  loop:
    print_it: 100
    max_it: 1000000
    val_it: 5000
    add_noise: false
  opt:
    lr: 3.0e-4
    weight_decay: 1.0e-2
    betas: [0.9, 0.999]