n_im_val_samples: 16
text_val_samples: [
    "A photograph of a young man with a beard",
    "A photograph of a old woman's face with grey hair",
    "A photograph of a child at a birthday party",
    "A picture of a face outside in bright sun in front of green grass",
    "This man has bangs arched eyebrows curly hair and a small nose",
    "A photo of Barack Obama",
    "An arctic explorer",
    "A clown's face covered in make up",
]